name: Metrics
on:
  # Mise à jour toutes les 6 heures
  schedule: [{cron: "0 */6 * * *"}]
  # Permet de lancer manuellement
  workflow_dispatch:
  # Lance à chaque push
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token GitHub (à configurer dans les secrets)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options de base
          user: luminescencedev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          config_display: large
          config_output: default
          
          # Plugin langages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          # Plugin lignes de code
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # Plugin contributions récentes
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
          
          # Plugin habitudes de code
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes
          
          # Thème sombre
          config_base: light
          extras_css: |
            * { color: #777777 !important; }
            .field { background: transparent !important; }
